USE WTW_CHAMPIONSHIP;

DROP TABLE CHECKIN;
DROP TABLE USER_ROLES;
DROP TABLE ROLE;
DROP TABLE USER;

CREATE TABLE IF NOT EXISTS USER (
    user_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    steam_name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    steam_url VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    active BOOLEAN NOT NULL,
	last_modification DATE NOT NULL
);
COMMIT;

CREATE TABLE IF NOT EXISTS ROLE (
	role_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL, -- official, steward, admin etc
	active BOOLEAN NOT NULL
);
COMMIT;

CREATE TABLE IF NOT EXISTS USER_ROLES (
	user_id BIGINT NOT NULL,
	role_id BIGINT NOT NULL,
    FOREIGN KEY (user_id)
        REFERENCES USER (user_id)
        ON UPDATE RESTRICT ON DELETE CASCADE,
    FOREIGN KEY (role_id)
        REFERENCES ROLE (role_id)
        ON UPDATE RESTRICT ON DELETE CASCADE
);
COMMIT;
	
	
CREATE TABLE IF NOT EXISTS CHECKIN (
	checkin_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    date DATE NOT NULL,
    will_attend BOOLEAN NOT NULL
);
COMMIT;